# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64fceb627822d2d3537eba15ab6a4a8f2f168652329cacc2f70807a993f084ca72370eb3a4b011f3fc64d88eefc14cc6dde24c3f829d9ba775ccb9963dfa0263

test:
  secret_key_base: 838992806a4d57819a54aaa33bb0331deead6c75bc862c2b9b2bb43683b0516f314e6ee4287c8e2a9a8068585af3034c89578491859496b23df402a689b5ed78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
